---
title: "Rodent trapping studies to understand the prevalence of zoonotic disease in West Africa: A scoping review."
description: |
date: "`r Sys.Date()`"
author: 
  - first_name: "David"
    last_name: "Simons"
    url: https://www.dsimons.org
    orcid_id: 0000-0001-9655-1656
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
    toc_float: true
  # word_document
knit: (function(inputFile, encoding) {
    rmarkdown::render(inputFile, encoding = encoding, output_dir = here::here())
  })
always_allow_html: yes
bibliography: "`r here::here('citations', 'manuscript_citations.bib')`"
---

# Introduction

  * The role of zoonotic infectious diseases in human health and society have been dramatically highlighted through the ongoing SARS-CoV-2 pandemic and recent Ebola virus outbreaks in the Democratic Republic of Congo and Guinea. 
  * The number and intensity of zoonotic spillover events is projected to increase under anthropogenic pressure (e.g. increased human populations and increasing urbanisation) and global climate change [@morse_prediction_2012].
  * Rodents are abundant and diverse [@burgin_how_2018], their widespread occurrence and proximity to human activity make the understanding of the effect of environmental change on their host-pathogen interactions vitally important. 
  * Rodents are important hosts of zoonotic disease. Of 2,220 extant rodent species, 244 (10.7%) are described as being reservoirs of 85 zoonotic pathogens [@han_global_2016]. This is an example of an ecosystem disservice provided by rodents.
  * Rodents, however, also provide important ecosystem services within these habitats, including, pest regulation and seed dispersal [@fischer_ecosystem_2018].
  * Rodents typically demonstrate “fast” life histories [@dobson_fast_2007] and within rodents, these traits are associated with a species being a reservoir of zoonotic diseases [@han_rodent_2015], but see [@albery_fast-lived_2021]. Further, these traits are prevalent in species that thrive in human dominated landscapes, displacing species that are less likely to be reservoirs of zoonotic disease [@gibb_zoonotic_2020].
  * West Africa has previously been identified to be at relatively high risk of emerging zoonotic infectious disease events from wildlife populations [@jones_global_2008]. Ongoing changes in land use and population demographics may lead to an increased burden from zoonotic diseases. 
  * Rodents are implicated in the transmission pathways of several diseases in the region, including, Lassa fever, Schistosomiasis and Leptospirosis.
  * Studies have been conducted in West Africa both to identify novel potential zoonotic pathogens within rodents alongside studies investigating the prevalence and burden of known pathogens within rodent hosts (e.g. for Lassa fever [@fichet-calvet_diversity_2009] and Schistosomiasis [@catalano_multihost_2020]).
  * Our understanding of the associations between rodents and their pathogens on broader geographic scales are typically based on global datasets (e.g. PREDICTS, GIDEON and GBIF) that consolidate information obtained from multiple sources of information [@gibb_zoonotic_2020; @smith_global_2014; @pigott_mapping_2014]. These datasets may lack the contextually rich information on the presence, absence and abundance of individual species and the habitats in which they were trapped that is potentially provided by individual rodent trapping studies [@bovendorp_optimising_2017].
  * Alongside disease specific studies these datasets have been used to identify potential geographic hotspots where virus and host species diversity may be expected to be at its greatest and therefore quantify the risk of a zoonotic disease spillover event occurring at a defined location [@han_global_2016]. However, there remains the potential for important confounding introduced to these associations through bias generated by study design or through selection of sampling sites.
  * For example, systematically increased sampling (e.g. more intensive studies over longer time periods) or over-representation of certain habitats (e.g. periurban landscapes) could lead to an apparent association between locations and risk that is driven by these factors rather than an underlying host and virus association [@wille_how_2021; @gibb_mammal_2021].
  * Conversely some regions may not be sampled adequately and therefore under-represented in these datasets due to sparse human populations or inaccessible habitats which may lead to erroneously identifying regions as low risk of zoonotic disease spillover events.
  * Here, we identify rodent trapping studies performed across West Africa and identify the location and habitat types in which they have been conducted, the pathogens assessed and the host-pathogen associations that have been reported in order to quantify the potential bias and identify areas requiring further focussed investigation.

# Methods

## Literature search

  * We conducted a search in Ovid MEDLINE, Web of Science (Core collection and Zoological Record), JSTOR, BioOne, African Journals Online, Global Health and the pre-print servers, BioRxiv and EcoEvoRxiv for the following terms as keywords, no date constraints were used: 
  
    1. Rodent OR Rodent trap*
    2. West Africa (or the individual countries)
    3. 1. AND 2.

  * We searched other resources including the UN Official Documents System, Open Grey, AGRIS FAO and Google Scholar using combinations of the above terms.
  * We ran the search on 2021-03-01.
  * We included studies if they met all of the following inclusion criteria; i) reported findings from trapping studies where the target was a small mammal, ii) described the type of trap used or the length of trapping activity or the location of the trapping activity, iii) included trapping activity from at least one West African country, iv) recorded the genus or species of trapped individuals, v) were published in a peer-reviewed journal or as a pre-print on a digital platform or as a report by a credible organisation.
  * We excluded studies if they met any of the following exclusion criteria: i) reported data that were duplicated from a previously included study, ii) no full text available, iii) not available in English.
  * One reviewer screened titles, abstracts and full texts against the inclusion and exclusion criteria. At each stage, a random subset (10%) was reviewed by a second reviewer.    
  
## Data extraction

  * We extracted data from eligible studies to input into a Google sheets document. Extracted variables included i) study identifiers; ii) study aims; iii) trapping methodology; iv) geolocation data; v) method of speciation; vi) trapping locations and dates; vii) trapped species; viii) number of trap-nights and ix) microorganisms/pathogens of interest. The data extraction tool is archived and available in Supplementary Material 1. 

### Location of rodent trapping studies and habitats studied
  * We extracted GPS locations for the most precise location presented (i.e. trap, trap-line, study site or study region). We extracted coordinates in the format reported, subsequently converting them to decimal degrees. 
  * We recorded the habitat classification scheme a study used (e.g.  IUCN Habitat Classification Scheme (Version 3.1)). For studies not using standardised recording, the explicit description from of the habitat in which the trap was placed was extracted. For studies reporting multiple habitat types (e.g. rice field, corn field and vegetable garden) for a single trap, trap-line or trapping grid, a higher order classification of habitat type was recorded (e.g.  agricultural land).

### Rodent presence, absence, abundance
  * We mapped genus and species names to the species names used in the GLobal Biodiversity Information Facility (GBIF) taxonomy  [@gbif_the_global_biodiversity_information_facility_global_2021]
  * We extracted information on the presence, absence and number of trapped individuals. For studies reporting on all trapped individuals (i.e. not those only reporting on the presence of a specific species of interest), the pseudo-absence of a species reported as present elsewhere in the study was explicitly recorded as an absence at that trap location.

### Pathogen presence and absence
  * We extracted data on all pathogens assayed for in studies investigating rodents for potential zoonoses. The number of rodents tested and the number of positive or negative samples were recorded alongside the type of assay used (e.g. Polymerase Chain Reaction (PCR), Enzyme Linked ImmunoSorbent Assay (ELISA) or viral culture). If studies reported indeterminate results this was noted. Where possible, pathogens were identified to species level. However, where an assay only allowed for attribution to a family of viruses or bacteria, the higher order grouping was used (i.e. PCR using a non-specific arenavirus primer).

## Analysis

### Location and habitats of rodent trapping to investigate potential biases

  * We summarised the number of studies, the year in which trapping occurred and the country in which they were conducted. In studies not reporting the year of trapping we used the year of publication as a proxy.
  * We used the GPS coordinates of single trap, trapping grid/line or study site and the number of trap nights to calculate trapping effort (trap night density) within level 2 administrative areas in West Africa. 
  * For studies not reporting the number of trap nights we imputed the number based on the median trap success rate from studies which reported the number of trap nights (matched to building or non-building based study sites). The median trap success rate for all rodents at a defined trap site was calculated for both trap sites including built environments and non-built environments. The number of rodents trapped at a trap site was then used in combination with these values of trap success to impute the number of trap nights for trap sites with no reported trap nights.
  * We summarised the habitat types of trap sites based on information reported in the study.
  * For the subset of studies investigating rodent zoonoses we compared the location of trapping sites with 2005 SEDAC Global Population Density estimates, the median year studies were commenced, using a Generalised Additive Model (GAM) incorporating a spatial interaction term to investigate the association of number of trap nights and human population density. The model structure was specified as below:
    * *trap night density* ~ *Tweedie*(*log*(Population density (2005)) + (Longitude * Latitude))   
  * We repeated this approach for land cover classifications obtained from the European Space Agency Copernicus dataset (2005) using a GAM incorporating a spatial interaction term to investigate the association of trap nights and land cover.
  * We mapped the presence and absence of rodent species and compared this to the presence and absence reported by both GBIF and IUCN to give a measure of the extent of each species range in which they have been sampled. 

### Rodent pathogen associations

  * We summarised the presence and absence of pathogens, the assays used, their host species and the locations from where the samples were obtained.
  * We investigated the association between rodent species and the detection of potential pathogens. We report proportion of positive and negative tests for each species and pathogen pair.

# Results

## Included studies

  * 4,282 citations were identified, with 126 rodent trapping studies included in narrative synthesis.
  * The earliest included studies were from 1974 with increasing numbers of studies being performed annually since 2005.
  * The median length of rodent trapping activity is one year (IQR 0-2 years). The median time from completion of rodent trapping to publication is 3 years (IQR 2-5 years) (see Figure 1 - Panel A).

## Location and habitats of rodent trapping studies to investigate potential biases

  * Rodent trapping took place across 1,331 trap sites with at least one trap site recorded from 14 West African countries. No rodent trapping studies were identified from Gambia or Togo.
  * Thirty-one (25%) studies reported trapping at a single study site, 46 (37%) studies trapped at between two and five study sites, the remaining 49 studies trapped at between six and 93 study sites. Trap sites were situated in 273 (19.3%) of 1414 level 2 administrative regions from the 14 West African nations. The areas with highest trapping activity included the capital cities of Niger (Niamey), Sierra Leone (Freetown), Senegal (Dakar), Mali (Bamako) and Ghana (Accra) and the largest cities of Ivory Coast (Abidjan) and Benin (Cotonou). Outside of these cities, Northern Senegal (Fatique, Thies, Saint-Louis and Kedougou), Southern Guinea (Kindia and Nzerejore), Edo and Osun States in Nigeria and Eastern Sierra Leone were the most intensively studied regions (see Figure 1 - Panel B).
  * Greater numbers of trap nights were conducted in areas with higher population densities (*R~2~* = 0.167). In particular Mauritania, Northern Senegal, Eastern Sierra Leone, Eastern Guinea and South West Nigeria were trapped at increased rates than would be expected based on their population densities. South West Nigeria, Northern Nigeria, Liberia, the Ivory Coast, Ghana, Niger and Burkina Faso were trapped at lower rates.
  * No studies reported trap habitats with reference to a standardised habitat classification scheme. 
  * Extracted habitat types were grouped into 30 categories (see Supplementary Material 2 for the habitat dictionary). At least one habitat was recorded for 17,122 trap sites (95%), with two or more habitats for a single trap site recorded for 4,403 (24%) sites. Single trap sites could span multiple habitat types resulting in 22,202 distinct habitat and trap sites. 
  * The most commonly trapped sites were in or around buildings (29%), in areas described as the rodents “natural habitat” (24%), in agricultural areas (13%) (e.g. rice fields, palm plantations), forests (8%) and in the area surrounding buildings (4%).
  * Explore whether trap sites are more likely to have been conducted within high population regions or whether there is an association with trap location and habitat as obtained from remote sensing data (Need to do this. The remote sensing data will be matched to the trap dates there will be several years between the trapping and data this is compared to it seems impractical to try and get annual population estimates or land classification so this will be chosen pragmatically)

```{r, figure_1}

cowplot::plot_grid(plotlist = )

```

Figure 1 - Panel A - plot of studies, Panel B - location of traps, Panel C - The distribution of population density at trap sites, Panel D- The distribution of habitat types at trap sites compared to all habitat types in West Africa

Figure 1: **Panel A:** Each row represents one of the 126 included studies, green points designate the first year of data collection, blue points designate the end of data collection. For studies completed within one year the blue point overlies the green. Studies with a transparent grey point did not report the year in which trapping was conducted. The year of publication is shown by a red point. **Panel B:** Map of West Africa, countries where rodent trapping has occurred are mapped to level 2 administrative areas (where available). These regions are coloured by the total number of trap nights performed at trap sites within their boundaries. **Panel C:** Histogram of human population density at 5km^2^ resolution across West Africa and for areas where trapping has occurred. **Panel D:** Histogram of habitat types at 1km^2^ resolution across West Africa and for areas where trapping has occurred.

## Rodent presence, absence, abundance
  * 73,164 small mammals were trapped (592 were trapped outside of West African countries), 2,830 (4%) trapped individuals were identified to order level (Rodentia), 7,760 (11%) were identified to genus level, the remaining 62,574 (85%) were identified to species level. 
  * In studies reporting the number of trap nights the median trap success rate of traps placed in or around buildings was 13% (IQR 6-24%), this compares to a median trap success rate of 3% (IQR 1-9%) in other habitats.
  * Of the 147 distinct identified species trapped (see Supplementary Material 3) the majority were from the order Rodentia (112). Muridae (82) represented the largest family of rodents, followed by, Sciuridae (10), Gliridae and Nesomyidae (both 6), Ctenodactylidae and Anomaluridae (2) and Dipodidae, Hystricidae and Thryonomidae (all 1). The remaining 34 species came from the orders of the Soricomorpha (30), Erinaceomorpha (2) and Afrosoricida (1).
  * The most commonly trapped genera of rodents were Mastomys sp. (27,072, 38.5%), Rattus sp. (10,191, 14.5%), Mus sp. (8,624, 12.3%), Arvicanthis sp. (5,821, 8.3%) and Praomys sp. (5,409, 7.7%). At species level Mastomys natalensis (11,221, 17.9%), Rattus rattus (8,578, 13.7%), Mastomys erythroleucus (7,379, 11.8%), Mus musculus (6,245, 10%), Arvicanthis niloticus (5,497, 8.8%) and Mastomys huberti (4,699, 7.5%) were the most commonly trapped. 
  * Presence and absence maps for the six most commonly trapped species are compared to GBIF and IUCN data. (Need to do this)
  * The number of individuals trapped provides a measure of abundance, the interpretation of this is limited by incomplete reporting on the trapping effort (i.e. number of trap nights) within a study. The most abundant species at presence locations were … (Need to do this. I will explore the number of individuals trapped by species, I imagine it will show that if a species is detected at a site the most abundant ones will be the synanthropic species such as mus, rattus etc. while the more specialised species will be less abundant in areas where they are detected)

Figure 2 - Three plots side by side with 6 rows, one each for the most commonly trapped species Panel A - presence/absence from this review, Panel B - presence/absence from GBIF, Panel C - Species range from IUCN

Figure 2 - **Panel A** shows the presence and absence of the 6 most commonly trapped rodent species from the current study. The perimeter polygon (blue) is the convex hull of the observation points produced from presence only data. **Panel B**  

## Pathogen presence and absence
  * Sixty-two studies presented data on microorganisms that infect or are carried by small mammal species in West Africa.
  * Seven studies solely investigated pathogens of rodents, including Hydatigera species (previously Taenia species) and Trichuris species.
  * Fifty-five studies investigated organisms that were potentially zoonotic pathogens. Thirty-two microorganisms were tested for, 8 of these were defined at species level, with the remaining 24 at levels of higher taxonomic classification.
  * Thirty-two studies used Polymerase Chain Reaction (PCR) to detect the presence of 22 different species or families of microorganisms in 21,953 rodent samples. Eleven studies used antibody or antigen based molecular tests to detect the presence of 9 different species or families of microorganisms in 11,430 samples. Eight studies conducted histological or direct visualisation assays of samples for 11 parasitic or bacterial species in 11,229 samples. Three studies performed direct culture of Lassa mammarenavirus or Leishmania species to detect the presence of the pathogen in 643 samples.
  * The most common pathogens assessed for using PCR were Lassa mammarenavirus or other Arenaviridae (31%) the bacteria Borrelia sp. (11.3%) and Bartonella sp. (6.5%) followed by Usutu virus (6.4%) and Hantaviridae (5.6%). The most common pathogens assessed for with serology were Lassa mammarenavirus or other Arenaviridae (78%), Toxoplasma gondii (10.6%), Borrelia sp. (6.3%) and Leptospirosis sp. (2.2%). The most common pathogens assessed for with histology or direct visualisation were Borrelia sp. (48.7%), Schistosoma sp. (20.4%) and other parasites. All studies using direct culture were investigating either Lassa mammarenavirus (81%) or Leishmania sp. (19%). 
  * Most studies tested for a single pathogen (39), with 16 studies testing for two or more pathogens. The most frequently tested for pathogens were Lassa mammarenavirus (28%) or members of the Arenaviridae family (16%), the spirochete bacteria Borrelia sp. was investigated in 8 studies, Bartonella sp. and Toxoplasma gondii were investigated in 4 each, the remaining 25 pathogens were reported in three or fewer studies.
Define presence and absence of pathogens by country (Need to do)

Figure 3 - Presence/absence plots for the following pathogens Arenaviruses with LASV highlighted, Bartonella, Borrelia and Toxoplasma.

## Host-pathogen associations
  * Ninety-seven rodent species were investigated for the presence of a zoonotic pathogen. 42,940 assays were performed on 32,014 individual rodents. 
  * The rodent species most commonly assayed for zoonotic pathogens were, Rattus rattus (n = 2,977) assessed for 24 pathogens, Mus musculus (n = 3,402) for 23, Mastomys natalensis (n = 7,189) and Mastomys erythroleucus (n = 3,013) both 19 and Arvicanthis niloticus (n = 3,840) for 18.    * All remaining species were investigated for 10 or fewer pathogens.
  * Lassa mammarenavirus was detected in 414 Mastomys natalensis, 9 Mastomys erythroleucus, 5 Hylomyscus pamfi and 3 Mus baoulei through PCR. In serological assays, evidence of prior infection or acquisition of maternal antibodies to Lassa mammarenavirus was found in 465 Mastomys natalensis, 361 Mastomys sp., 6 Mus musculus and 4 Rattus rattus. From direct viral culture 19 Mastomys natalensis, 2 Rattus rattus and 1 Mus minutoides were found to be infected with Lassa mammarenavirus. Bartonella sp. were detected in; 113 Mastomys natalensis, 50 Mastomys erythroleucus, 39 Rattus norvegicus, 16 Rattus rattus and 13 individuals of 7 further species through PCR.
  * Borrelia sp. infections were identified through PCR in 110 individuals; 37 Mastomys erythroleucus, 12 Mus musculus, 11 Mastomys huberti and Praomys daltoni., tThe remaining 39 positive results were from 9 further species. In serological assays, 47 Mastomys natalensis, 12 Mastomys erythroleucus and 8 Praomys daltoni were found to be positive, the remaining 11 positive individuals came from three further species. Most Borrelia sp. infections were identified through histology or direct visualisation with, 243 Arvicanthis niloticus, 102 Mastomys natalensis, and 78 Mastomys huberti along with a further 64 individuals from 8 species infected.
  * Finally, Toxoplasma gondii was detected via PCR in 89 Mus musculus, 13 Cricetomys gambianus, 5 Crocidura olivieri and 3 Rattus rattus. From serological assays evidence of infection was found in 25 Mus musculus, 46 Mastomys erythroleucus, 4 Rattus rattus, and Mastomys natalensis, using histology and direct visualisation 1 Mus musculus and 1 Rattus rattus were also found to be infected.
  * Thirty-eight species of Rodentia, 3 species of Soricomorpha and 2 species of Erinaceomorpha that were tested for potential pathogens had entirely negative results.

Figure 4 - Matrix heat plot Y - rodent species/genera, X - pathogen species/genera. Colour relates to proportion positive (Perhaps use bivariate colour to also highlight the number of test performed in that species).

## Discussion    
  
  * 124 trapping studies were identified across 14 West African countries. 54 studies provided additional information about potential zoonotic pathogens of trapped rodents.
